# Generated by Django 4.0.3 on 2022-04-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0002_website_delete_websites_alter_vmlist_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VmList',
            new_name='Vm',
        ),
    ]
