# Generated by Django 3.1.4 on 2022-04-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0006_auto_20220415_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
