# Generated by Django 3.1.4 on 2022-04-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0010_auto_20220427_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='dns_network_status',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='DNS Network Status'),
        ),
        migrations.AddField(
            model_name='website',
            name='vm_network_status',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='VM Network Status'),
        ),
    ]
