# Generated by Django 3.1.4 on 2022-05-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0014_auto_20220506_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='calc_ping_field',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User'),
        ),
    ]
