# Generated by Django 3.1.4 on 2022-10-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0019_auto_20220928_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='ssl_certificate_action',
            field=models.TextField(blank=True, null=True, verbose_name='SSL Certificate Action'),
        ),
    ]
