# Generated by Django 3.1.4 on 2024-10-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0024_auto_20221115_1044'),
        ('lddt_app', '0033_auto_20230721_1101'),
    ]

    operations = [
    ]
