# Generated by Django 4.0.3 on 2022-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssl_expiry_date', models.DateField(blank=True, default=None, null=True)),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('function', models.CharField(blank=True, max_length=150, null=True, verbose_name='Function')),
                ('server', models.CharField(blank=True, max_length=150, null=True, verbose_name='Server')),
                ('ip_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='IP Address')),
                ('vulnerability_checked', models.CharField(blank=True, max_length=150, null=True, verbose_name='Vulnerability')),
                ('personal_data_held', models.CharField(blank=True, max_length=150, null=True, verbose_name='Personal Data')),
                ('port', models.CharField(blank=True, max_length=150, null=True, verbose_name='Port')),
                ('load_balancer', models.CharField(blank=True, max_length=150, null=True, verbose_name='Load Balancer')),
                ('ours', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ours')),
                ('environment', models.CharField(blank=True, max_length=150, null=True, verbose_name='Environment')),
                ('ssl_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='SSL Type')),
                ('ease_expiry', models.DateField(blank=True, max_length=150, null=True, verbose_name='EASE Expiry')),
                ('application', models.CharField(blank=True, max_length=150, null=True, verbose_name='Application')),
                ('restore_action', models.TextField(blank=True, null=True, verbose_name='Restore Action')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('major_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='Major User')),
                ('external_support', models.CharField(blank=True, max_length=150, null=True, verbose_name='External Support')),
                ('expected_response', models.CharField(blank=True, max_length=150, null=True, verbose_name='Expected Response')),
                ('handle_prefix', models.CharField(blank=True, max_length=150, null=True, verbose_name='Handle Prefix')),
                ('accessibility_statement', models.CharField(blank=True, max_length=150, null=True, verbose_name='Accessibility Statement')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.DeleteModel(
            name='Websites',
        ),
        migrations.AlterField(
            model_name='vmlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
