# Generated by Django 3.1.4 on 2022-04-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0003_rename_vmlist_vm'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='group',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='vm',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='website',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
