# Generated by Django 3.1.4 on 2022-04-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0004_auto_20220411_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='hostname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Hostname'),
        ),
    ]
