# Generated by Django 3.1.4 on 2022-04-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0007_auto_20220426_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL'),
        ),
    ]
