# Generated by Django 3.1.4 on 2022-11-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0021_auto_20221010_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='access_statement_y_n',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='website',
            name='access_statement_y_n',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lddt_app.access_statement_y_n'),
        ),
    ]
