# Generated by Django 3.1.4 on 2022-11-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0023_accessstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessstatement',
            name='expiry_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='accessstatement',
            name='testing_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
