# Generated by Django 3.1.4 on 2022-11-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0024_auto_20221116_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessstatement',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='accessstatement',
            name='how_deploy',
            field=models.TextField(blank=True, null=True, verbose_name='How to deploy'),
        ),
    ]
