# Generated by Django 3.2.8 on 2023-03-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0030_auto_20230207_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessstatement',
            name='issues_target_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='accessstatement',
            name='re_test_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='accessstatement',
            name='statement_status_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
