# Generated by Django 3.1.4 on 2024-10-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0035_auto_20241002_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='vmfs_data_used',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='VMFS-data used'),
        ),
    ]
