# Generated by Django 2.2.12 on 2022-04-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VmList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='IP Address')),
                ('application', models.CharField(blank=True, max_length=150, null=True, verbose_name='Application')),
                ('ssh_in_lp', models.CharField(blank=True, max_length=150, null=True, verbose_name='SSH in LP')),
                ('puppet_controlled', models.CharField(blank=True, max_length=150, null=True, verbose_name='Puppet Controlled')),
                ('data_centre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Data Centre')),
                ('poodle_checked', models.CharField(blank=True, max_length=150, null=True, verbose_name='Poodle Checked')),
                ('log4shell_risk', models.CharField(blank=True, max_length=150, null=True, verbose_name='Log for shell risk')),
                ('trace_risk', models.CharField(blank=True, max_length=150, null=True, verbose_name='Trace Risk')),
                ('httpd_last_patch', models.DateField(blank=True, max_length=150, null=True, verbose_name='HTTPD Last patch')),
                ('os_centos_assumed', models.CharField(blank=True, max_length=150, null=True, verbose_name='OS (CENTOS assumed)')),
                ('httpd', models.CharField(blank=True, max_length=150, null=True, verbose_name='HTTPD')),
                ('tomcat', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tomcat')),
                ('nginx', models.CharField(blank=True, max_length=150, null=True, verbose_name='NGINX')),
                ('ram', models.CharField(blank=True, max_length=150, null=True, verbose_name='RAM')),
                ('cpu', models.CharField(blank=True, max_length=150, null=True, verbose_name='CPU')),
                ('db', models.CharField(blank=True, max_length=150, null=True, verbose_name='DB')),
                ('php', models.CharField(blank=True, max_length=150, null=True, verbose_name='PHP')),
                ('java', models.CharField(blank=True, max_length=150, null=True, verbose_name='Java')),
                ('vm_storage', models.CharField(blank=True, max_length=150, null=True, verbose_name='VM Storage')),
                ('special_mounts', models.CharField(blank=True, max_length=150, null=True, verbose_name='Special Mounts')),
                ('python', models.CharField(blank=True, max_length=150, null=True, verbose_name='Python')),
                ('npm', models.CharField(blank=True, max_length=150, null=True, verbose_name='NPM')),
                ('shibboleth', models.CharField(blank=True, max_length=150, null=True, verbose_name='NPM')),
                ('ssl', models.CharField(blank=True, max_length=150, null=True, verbose_name='SSL')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssl_expiry_date', models.DateField(blank=True, default=None, null=True)),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('function', models.CharField(blank=True, max_length=150, null=True, verbose_name='Function')),
                ('server', models.CharField(blank=True, max_length=150, null=True, verbose_name='Server')),
                ('ip_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='IP Address')),
                ('vulnerability_checked', models.CharField(blank=True, max_length=150, null=True, verbose_name='Vulnerability')),
                ('personal_data_held', models.CharField(blank=True, max_length=150, null=True, verbose_name='Personal Data')),
                ('port', models.CharField(blank=True, max_length=150, null=True, verbose_name='Port')),
                ('load_balancer', models.CharField(blank=True, max_length=150, null=True, verbose_name='Load Balancer')),
                ('ours', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ours')),
                ('environment', models.CharField(blank=True, max_length=150, null=True, verbose_name='Environment')),
                ('ssl_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='SSL Type')),
                ('ease_expiry', models.DateField(blank=True, max_length=150, null=True, verbose_name='EASE Expiry')),
                ('application', models.CharField(blank=True, max_length=150, null=True, verbose_name='Application')),
                ('restore_action', models.TextField(blank=True, null=True, verbose_name='Restore Action')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('major_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='Major User')),
                ('external_support', models.CharField(blank=True, max_length=150, null=True, verbose_name='External Support')),
                ('expected_response', models.CharField(blank=True, max_length=150, null=True, verbose_name='Expected Response')),
                ('handle_prefix', models.CharField(blank=True, max_length=150, null=True, verbose_name='Handle Prefix')),
                ('accessibility_statement', models.CharField(blank=True, max_length=150, null=True, verbose_name='Accessibility Statement')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
    ]
