# Generated by Django 3.1.4 on 2022-04-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0011_auto_20220428_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='dns_ip_address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='DNS IP Address'),
        ),
        migrations.AlterField(
            model_name='website',
            name='vm_ip_address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='VM IP Address'),
        ),
    ]
