# Generated by Django 3.1.4 on 2022-05-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0012_auto_20220428_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='website',
            name='dns_ip_address',
        ),
        migrations.RemoveField(
            model_name='website',
            name='dns_network_status',
        ),
        migrations.RemoveField(
            model_name='website',
            name='vm_network_status',
        ),
        migrations.AddField(
            model_name='website',
            name='tech_status',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='lddt_app.tech_status'),
        ),
        migrations.AddField(
            model_name='website',
            name='type',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='lddt_app.type'),
        ),
    ]
