# Generated by Django 3.1.4 on 2022-05-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0015_website_calc_ping_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='calc_ping_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
