# Generated by Django 3.1.4 on 2022-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0016_auto_20220512_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='calc_ping_field',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Field for ping'),
        ),
    ]
