# Generated by Django 3.1.4 on 2022-11-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0022_auto_20221107_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=150, null=True, verbose_name='URL')),
                ('word21', models.CharField(blank=True, max_length=150, null=True, verbose_name='WORD21')),
                ('jira_nr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jira No')),
                ('wa_statement_tasked_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='WA Statement tasked to')),
                ('site', models.CharField(blank=True, max_length=150, null=True, verbose_name='Site')),
                ('owning_team', models.CharField(blank=True, max_length=150, null=True, verbose_name='Owning Team')),
                ('content_service_manager', models.CharField(blank=True, max_length=150, null=True, verbose_name='Content Service Manager')),
                ('tech_contact', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tech Contact')),
                ('architecture', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tech Contact')),
                ('physical_location_server', models.CharField(blank=True, max_length=200, null=True, verbose_name='Physical Location Server')),
                ('physical_location_directory_file', models.CharField(blank=True, max_length=200, null=True, verbose_name='Physical Location Directory-File')),
                ('how_deploy', models.CharField(blank=True, max_length=200, null=True, verbose_name='How to deploy')),
                ('testing_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Testing Status')),
                ('access_statement_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Accessibility Statement Status')),
            ],
        ),
    ]
