# Generated by Django 3.1.4 on 2022-11-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0023_accessstatement'),
    ]

    operations = [

        
    ]
