# Generated by Django 3.1.4 on 2022-11-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0026_auto_20221122_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement_Status_r',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='accessstatement',
            name='access_statement_status_r',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='lddt_app.statement_status_r'),
        ),
    ]
