# Generated by Django 3.1.4 on 2022-11-29 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0027_auto_20221122_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ga4_y_n',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='website',
            name='ga4_notes',
            field=models.TextField(blank=True, null=True, verbose_name='GA4 Notes'),
        ),
        migrations.AddField(
            model_name='website',
            name='ga4_path',
            field=models.TextField(blank=True, null=True, verbose_name='GA4 path'),
        ),
        migrations.AddField(
            model_name='website',
            name='ga4_y_n',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lddt_app.ga4_y_n'),
        ),
    ]
