# Generated by Django 3.2.8 on 2023-02-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0029_auto_20230131_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasked_to',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='accessstatement',
            name='wa_statement_tasked_to_r',
        ),
        migrations.DeleteModel(
            name='Statement_Tasked_to_r',
        ),
        migrations.AddField(
            model_name='accessstatement',
            name='wa_statement_tasked_to_last',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='lddt_app.tasked_to'),
        ),
    ]
