# Generated by Django 4.2.9 on 2025-11-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0037_alter_access_statement_y_n_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='ssl_certificate_expiry',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='VMFS-data used'),
        ),
    ]
