# Generated by Django 4.2.9 on 2025-12-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0038_vm_ssl_certificate_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='ssl_expiry_date_new',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='ssl_certificate_expiry',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SSL-Cert Expiry'),
        ),
    ]
