# Generated by Django 4.2.9 on 2025-12-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0039_website_ssl_expiry_date_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm',
            name='ssl_certificate_expiry',
        ),
        migrations.AddField(
            model_name='vm',
            name='processors',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Processors'),
        ),
    ]
