# Generated by Django 4.2.9 on 2025-12-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0040_remove_vm_ssl_certificate_expiry_vm_processors'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='memory',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Memory'),
        ),
    ]
