# Generated by Django 4.2.9 on 2025-12-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0041_vm_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='last_patch_days_ago',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Last Patch in days ago'),
        ),
    ]
