# Generated by Django 4.2.9 on 2025-12-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0042_vm_last_patch_days_ago'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='system_check',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='System Check'),
        ),
    ]
