# Generated by Django 4.2.9 on 2026-01-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0043_vm_system_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='last_health_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
