# Generated by Django 4.2.9 on 2026-01-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0044_vm_last_health_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('active_users', models.IntegerField()),
                ('sessions', models.IntegerField()),
                ('page_views', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
