# Generated by Django 4.2.9 on 2026-01-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0044_vm_last_health_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalyticsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=32)),
                ('property_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('daily_users', models.IntegerField(default=0)),
                ('monthly_users', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Google Analytics Stat',
                'verbose_name_plural': 'Google Analytics Stats',
                'unique_together': {('property_id', 'date')},
            },
        ),
    ]
