# Generated by Django 4.2.9 on 2026-01-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0045_analyticsstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsstat',
            name='property_id',
            field=models.CharField(default='unknown_property', max_length=32),
        ),
        migrations.AddField(
            model_name='analyticsstat',
            name='property_name',
            field=models.CharField(default='unknown_property_name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='analyticsstat',
            unique_together={('property_id', 'date')},
        ),
        migrations.RemoveField(
            model_name='analyticsstat',
            name='created_at',
        ),
    ]
