# Generated by Django 4.2.9 on 2026-01-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0045_googleanalyticsstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleanalyticsstats',
            name='earliest_data_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
