# Generated by Django 4.2.9 on 2026-01-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0046_googleanalyticsstats_earliest_data_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalyticsMonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=32)),
                ('property_name', models.CharField(max_length=255)),
                ('year_month', models.CharField(max_length=6)),
                ('users', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['year_month'],
                'unique_together': {('property_id', 'year_month')},
            },
        ),
    ]
