# Generated by Django 4.2.9 on 2026-01-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0047_googleanalyticsmonthlystats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleAnalyticsMonthlyStats',
        ),
        migrations.AddField(
            model_name='googleanalyticsstats',
            name='monthly_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
