# Generated by Django 4.2.9 on 2026-01-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0049_googleanalyticsmonthlystats'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalyticsdats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=32)),
                ('property_name', models.CharField(max_length=255)),
                ('year_month', models.CharField(max_length=6)),
                ('users', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['year_month'],
                'unique_together': {('property_id', 'year_month')},
            },
        ),
        migrations.DeleteModel(
            name='GoogleAnalyticsMonthlyStats',
        ),
        migrations.RemoveField(
            model_name='googleanalyticsstats',
            name='monthly_data',
        ),
        migrations.AddField(
            model_name='googleanalyticsstats',
            name='monthly_sessions_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='googleanalyticsstats',
            name='monthly_users_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
