# Generated by Django 4.2.9 on 2026-01-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0050_googleanalyticsdats_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleAnalyticsdats',
        ),
    ]
