# Generated by Django 4.2.9 on 2026-01-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0051_delete_googleanalyticsdats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleanalyticsstats',
            options={'ordering': ['-snapshot_date'], 'verbose_name': 'Google Analytics Stat', 'verbose_name_plural': 'Google Analytics Stats'},
        ),
        migrations.AlterUniqueTogether(
            name='googleanalyticsstats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='googleanalyticsstats',
            name='snapshot_date',
            field=models.DateField(default='2026-01-16'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googleanalyticsstats',
            name='daily_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='googleanalyticsstats',
            name='monthly_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='googleanalyticsstats',
            unique_together={('property_id', 'snapshot_date')},
        ),
        migrations.RemoveField(
            model_name='googleanalyticsstats',
            name='date',
        ),
    ]
