# Generated by Django 4.2.9 on 2026-01-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0052_alter_googleanalyticsstats_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleanalyticsstats',
            options={'ordering': ['-date'], 'verbose_name': 'Google Analytics Stat', 'verbose_name_plural': 'Google Analytics Stats'},
        ),
        migrations.RenameField(
            model_name='googleanalyticsstats',
            old_name='snapshot_date',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='googleanalyticsstats',
            unique_together={('property_id', 'date')},
        ),
    ]
