# Generated by Django 4.2.9 on 2026-02-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lddt_app", "0053_alter_googleanalyticsstats_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="googleanalyticsstats",
            index=models.Index(
                fields=["property_id", "date"],
                name="idx_ga_stats_prop_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="googleanalyticsstats",
            constraint=models.UniqueConstraint(
                fields=("property_id", "date"),
                name="uniq_ga_stats_property_date",
            ),
        ),
    ]
