# Generated by Django 4.2.9 on 2026-02-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0054_alter_googleanalyticsstats_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleanalyticsstats',
            options={'ordering': ['property_name'], 'verbose_name': 'Google Analytics Stat', 'verbose_name_plural': 'Google Analytics Stats'},
        ),
        migrations.RemoveConstraint(
            model_name='googleanalyticsstats',
            name='uniq_ga_stats_property_date',
        ),
        migrations.RemoveIndex(
            model_name='googleanalyticsstats',
            name='idx_ga_stats_prop_date',
        ),
        migrations.AlterUniqueTogether(
            name='googleanalyticsstats',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='googleanalyticsstats',
            name='property_id',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AddIndex(
            model_name='googleanalyticsstats',
            index=models.Index(fields=['property_id'], name='idx_ga_stats_prop'),
        ),
    ]
