# Generated by Django 4.2.9 on 2026-03-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0055_alter_googleanalyticsstats_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='fetch_details',
            field=models.BooleanField(default=True),
        ),
    ]
