# Generated by Django 4.2.9 on 2026-03-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0056_vm_fetch_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='last_cron_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
