# Generated by Django 4.2.9 on 2026-05-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0057_vm_last_cron_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='url_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
