# Generated by Django 4.2.9 on 2026-05-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0058_website_url_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='ssl_certificate_provider',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SSL Certificate Provider'),
        ),
    ]
