# Generated by Django 4.2.9 on 2026-05-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0059_website_ssl_certificate_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='url_access_scope',
            field=models.CharField(blank=True, choices=[('GLOBAL', 'Global'), ('EDLAN_ONLY', 'EdLan-only')], max_length=20, null=True, verbose_name='URL Access Scope'),
        ),
    ]
