# Generated by Django 4.2.9 on 2026-05-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0060_website_url_access_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='url_access_scope_manual',
            field=models.BooleanField(default=False),
        ),
    ]
