# Generated by Django 4.2.9 on 2026-05-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0061_website_url_access_scope_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='http_check_status',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('BLOCKED', 'BLOCKED'), ('REDIRECT', 'REDIRECT'), ('OFFLINE', 'OFFLINE'), ('SSL_ERROR', 'SSL ERROR'), ('ERROR', 'ERROR')], max_length=20, null=True, verbose_name='HTTP Check Status'),
        ),
        migrations.AddField(
            model_name='website',
            name='http_status_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='HTTP Status Code'),
        ),
        migrations.AddField(
            model_name='website',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Checked'),
        ),
        migrations.AddField(
            model_name='website',
            name='last_error',
            field=models.TextField(blank=True, null=True, verbose_name='Last Error'),
        ),
        migrations.AddField(
            model_name='website',
            name='response_time_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Response Time ms'),
        ),
    ]
