# Generated by Django 4.2.9 on 2026-05-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0062_website_http_check_status_website_http_status_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleanalyticsstats',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
