# Generated by Django 4.2.9 on 2026-05-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0063_googleanalyticsstats_last_synced_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleanalyticsstats',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='googleanalyticsstats',
            name='idx_ga_stats_prop',
        ),
        migrations.AddField(
            model_name='googleanalyticsstats',
            name='monthly_views_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
