# Generated by Django 4.2.30 on 2026-08-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lddt_app', '0064_alter_googleanalyticsstats_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleanalyticsstats',
            name='ga4_measurement_ids',
            field=models.JSONField(blank=True, default=list, help_text='GA4 Measurement IDs belonging to this property'),
        ),
    ]
